Repository contiamo/operational-ui, pull requests merged in 2018-06, with the labels that each got.

#472 Tune sidenav
  package.json
  packages/components/scripts/dev-server/index.tsx
  packages/components/src/SidenavHeader/SidenavHeader.tsx
  packages/components/src/SidenavItem/SidenavItem.tsx
  packages/components/src/__tests__/__snapshots__/Header.test.tsx.snap
  packages/components/src/__tests__/__snapshots__/Sidenav.test.tsx.snap
  packages/theme/src/index.ts
  yarn.lock
Labels: ✅ Can merge

#469 Enhance readmes
  README.md
  packages/components/README.md
  packages/components/src/ButtonGroup/README.md
  packages/components/src/Messages/README.md
  packages/components/src/OperationalUI/README.md
  packages/components/src/Record/README.md
  packages/components/src/Sidenav/README.md
  packages/components/src/Sidenav/Sidenav.tsx
  packages/components/src/SidenavHeader/SidenavHeader.tsx
  packages/components/src/utils/deprecate.tsx
  packages/components/webpack.config.js
  packages/website/package.json
Labels: ✅ Can merge

#474 Split the build & deploy website scripts
  package.json
  packages/components/package.json
  packages/theme/package.json
  packages/utils/package.json
  packages/visual-tests/package.json
  packages/visualizations/package.json
  packages/website/package.json
  yarn.lock
Labels: utils

#480 Fix d3 utils for path attrTween transitions.
  packages/visualizations/src/Chart/series/renderers/flag.ts
  packages/visualizations/src/PieChart/renderers/donut.ts
  packages/visualizations/src/PieChart/renderers/gauge.ts
  packages/visualizations/src/PieChart/renderers/polar.ts
  packages/visualizations/src/utils/d3_utils.ts
Labels: visualizations, ✅ Can merge

#483 Add scatterplot example.
  packages/visual-tests/src/TestCases/Chart/index.ts
  packages/visual-tests/src/TestCases/Chart/symbol-3.ts
Labels: Work in Progress, visualizations

#489 Fix tests on CI
  .travis.yml
  package.json
Labels: ✨ Enhancement

#484 AvatarGroup improvement
  .travis.yml
  package.json
  packages/components/package.json
  packages/components/src/Avatar/Avatar.tsx
  packages/components/src/Avatar/README.md
  packages/components/src/AvatarGroup/AvatarGroup.tsx
  packages/components/src/AvatarGroup/README.md
  packages/components/src/Messages/README.md
  packages/theme/package.json
  packages/utils/package.json
  packages/utils/src/__tests__/text.test.ts
  packages/utils/src/index.ts
  packages/utils/src/text.ts
  packages/visual-tests/src/TestCases/Chart/symbol-3.ts
  packages/visualizations/package.json
  yarn.lock
Labels: Redesign

#487 Chart focus customisation
  docs_legacy/visualizations/chart.md
  packages/visual-tests/src/TestCases/Chart/symbol-3.ts
  packages/visualizations/src/Chart/facade.ts
  packages/visualizations/src/Chart/focus.ts
  packages/visualizations/src/Chart/focus/element_focus.ts
  packages/visualizations/src/Chart/focus/styles.ts
  packages/visualizations/src/Chart/series/renderers/bars.ts
  packages/visualizations/src/Chart/series/renderers/symbol.ts
  packages/visualizations/src/Chart/typings.ts
  packages/website/src/Sections/Visualizations/Charts.tsx
Labels: visualizations

#490 Card and card header redesign
  packages/components/src/Card/Card.tsx
  packages/components/src/Card/README.md
  packages/components/src/CardColumn/CardColumn.tsx
  packages/components/src/CardColumn/README.md
  packages/components/src/CardColumns/CardColumns.tsx
  packages/components/src/CardColumns/README.md
  packages/components/src/CardHeader/CardHeader.tsx
  packages/components/src/CardHeader/README.md
  packages/components/src/__tests__/__snapshots__/Card.test.tsx.snap
  packages/components/src/__tests__/__snapshots__/Sidenav.test.tsx.snap
  packages/theme/src/index.ts
Labels: Redesign

#495 Add Status component
  packages/components/package.json
  packages/components/src/Status/README.md
  packages/components/src/Status/Status.tsx
  packages/components/src/types.ts
  yarn.lock
Labels: ✅ Can merge

#494 Update scatterplot example with axis titles and rotated axis labels.
  packages/visual-tests/src/TestCases/Chart/symbol-3.ts
  packages/visualizations/src/Chart/axes/categorical_axis.ts
  packages/visualizations/src/Chart/axes/quant_axis.ts
  packages/visualizations/src/Chart/axes/time_axis.ts
Labels: Bug, visualizations, ✅ Can merge

#496 Update default number formatter using d3-format.
  packages/visualizations/package.json
  packages/visualizations/src/Chart/facade.ts
  packages/visualizations/src/PieChart/facade.ts
  packages/visualizations/src/PieChart/typings.ts
  packages/visualizations/src/ProcessFlow/facade.ts
  packages/visualizations/src/Sunburst/facade.ts
  packages/visualizations/src/utils/__tests__/number_formatter.test.ts
  packages/visualizations/src/utils/number_formatter.ts
  yarn.lock
Labels: visualizations, ✅ Can merge

#497 Feature/resource list
  packages/components/src/Table/README.md
  packages/components/src/Table/Table.tsx
  packages/components/src/Typography/README.md
  packages/components/src/__tests__/__snapshots__/Sidenav.test.tsx.snap
  packages/components/src/__tests__/__snapshots__/Table.test.tsx.snap
  packages/components/src/utils/wrap-default-theme.tsx
Labels: Redesign, ✅ Can merge

#493 Feature/card element content
  packages/components/src/AvatarGroup/AvatarGroup.tsx
  packages/components/src/AvatarGroup/README.md
  packages/components/src/Card/Card.tsx
  packages/components/src/Card/README.md
  packages/components/src/CardColumn/CardColumn.tsx
  packages/components/src/CardColumns/CardColumns.tsx
  packages/components/src/CardColumns/README.md
  packages/components/src/CardHeader/CardHeader.tsx
  packages/components/src/CardHeader/README.md
  packages/components/src/CardItem/CardItem.tsx
  packages/components/src/CardItem/README.md
  packages/components/src/Record/README.md
  packages/components/src/Table/Table.tsx
  packages/components/src/Typography/README.md
  packages/components/src/__tests__/__snapshots__/Card.test.tsx.snap
  packages/components/src/index.ts
Labels: Redesign

#500 Update buttons
  packages/components/src/Button/Button.tsx
  packages/components/src/Button/README.md
  packages/components/src/Spinner/Spinner.tsx
  packages/components/src/__tests__/__snapshots__/Button.test.tsx.snap
  packages/components/src/__tests__/__snapshots__/ButtonGroup.test.tsx.snap
  packages/components/src/__tests__/__snapshots__/Spinner.test.tsx.snap
  packages/components/src/utils/color.ts
  packages/theme/src/constants.ts
  packages/theme/src/utils.ts
  packages/utils/src/color.ts
  packages/website/src/Sections/Components/Colors.tsx
Labels: Redesign, ⚛️ components

#503 Fix internal style adjustments
  packages/components/src/Breakdown/Breakdown.tsx
  packages/components/src/Button/Button.tsx
  packages/components/src/DatePicker/DatePicker.tsx
  packages/components/src/Input/Input.tsx
  packages/components/src/Input/README.md
  packages/components/src/Layout/Layout.tsx
  packages/components/src/Record/README.md
  packages/components/src/Textarea/Textarea.tsx
  packages/components/src/Timeline/README.md
  packages/components/src/Tooltip/README.md
  packages/components/src/Tooltip/Tooltip.tsx
  packages/components/src/__tests__/__snapshots__/Breakdown.test.tsx.snap
  packages/components/src/__tests__/__snapshots__/Tooltip.test.tsx.snap
Labels: ✅ Can merge

#509 Page component redesign
  packages/components/src/Button/Button.tsx
  packages/components/src/Button/README.md
  packages/components/src/Page/Page.tsx
  packages/components/src/Page/README.md
  packages/components/src/PageArea/PageArea.tsx
  packages/components/src/PageArea/README.md
  packages/components/src/Typography/Typography.tsx
  packages/components/src/__tests__/__snapshots__/Button.test.tsx.snap
  packages/components/src/__tests__/__snapshots__/ButtonGroup.test.tsx.snap
  packages/theme/src/constants.ts
  packages/theme/src/index.ts
  packages/utils/src/color.ts
Labels: Redesign, ⚛️ components, ✅ Can merge

#510 Improve button styling.
  packages/components/src/Button/Button.tsx
  packages/components/src/Button/README.md
  packages/components/src/__tests__/__snapshots__/Button.test.tsx.snap
  packages/components/src/__tests__/__snapshots__/ButtonGroup.test.tsx.snap
Labels: Redesign, ⚛️ components, ✅ Can merge

#505 Chip redesign.
  packages/components/src/Chip/Chip.tsx
  packages/components/src/Chip/README.md
  packages/components/src/__tests__/__snapshots__/Chip.test.tsx.snap
  packages/website/src/Sections/Components/Chips.tsx
Labels: Redesign, ⚛️ components, ✅ Can merge

#507 Paginator redesign.
  packages/components/src/Button/Button.tsx
  packages/components/src/Paginator/Paginator.tsx
  packages/components/src/Paginator/README.md
  packages/components/src/__tests__/Paginator.test.tsx
  packages/components/src/__tests__/__snapshots__/Button.test.tsx.snap
  packages/components/src/__tests__/__snapshots__/ButtonGroup.test.tsx.snap
  packages/components/src/__tests__/__snapshots__/Paginator.test.tsx.snap
  packages/website/src/Sections/Components/Paginators.tsx
  packages/website/src/Sections/Components/index.ts
Labels: Redesign, ⚛️ components, ✅ Can merge

#516 Remove css prop
  packages/components/src/Breadcrumb/Breadcrumb.tsx
  packages/components/src/Breadcrumbs/Breadcrumbs.tsx
  packages/components/src/Breakdown/Breakdown.tsx
  packages/components/src/Button/Button.tsx
  packages/components/src/ButtonGroup/ButtonGroup.tsx
  packages/components/src/CardHeader/CardHeader.tsx
  packages/components/src/Checkbox/Checkbox.tsx
  packages/components/src/Chip/Chip.tsx
  packages/components/src/ContextMenu/ContextMenu.tsx
  packages/components/src/ContextMenuItem/ContextMenuItem.tsx
  packages/components/src/DatePicker/DatePicker.tsx
  packages/components/src/Grid/Grid.tsx
  packages/components/src/Input/Input.tsx
  packages/components/src/Layout/Layout.tsx
  packages/components/src/Message/Message.tsx
  packages/components/src/Messages/Messages.tsx
  packages/components/src/Modal/Modal.tsx
  packages/components/src/Paginator/Paginator.tsx
  packages/components/src/Progress/Progress.tsx
  packages/components/src/Record/Record.tsx
  packages/components/src/Select/Select.Filter.tsx
  packages/components/src/Select/Select.Option.tsx
  packages/components/src/Sidebar/Sidebar.tsx
  packages/components/src/SidebarHeader/SidebarHeader.tsx
  packages/components/src/SidebarItem/SidebarItem.tsx
  packages/components/src/Sidenav/Sidenav.tsx
  packages/components/src/SidenavHeader/SidenavHeader.tsx
  packages/components/src/SidenavItem/SidenavItem.tsx
  packages/components/src/Switch/Switch.tsx
  packages/components/src/Tab/Tab.tsx
  packages/components/src/Tabs/Tabs.tsx
  packages/components/src/Textarea/Textarea.tsx
  packages/components/src/Tile/Tile.tsx
  packages/components/src/Timeline/Timeline.tsx
  packages/components/src/TimelineItem/TimelineItem.tsx
  packages/components/src/Tooltip/Tooltip.tsx
Labels: ✅ Can merge

#515 Fix UI regressions for inclusion in our products
  packages/components/src/Button/Button.tsx
  packages/components/src/Card/Card.tsx
  packages/components/src/Card/README.md
  packages/components/src/CardColumn/CardColumn.tsx
  packages/components/src/CardHeader/CardHeader.tsx
  packages/components/src/CardHeader/README.md
  packages/components/src/CardItem/CardItem.tsx
  packages/components/src/HeaderBar/HeaderBar.tsx
  packages/components/src/Icon/Icon.tsx
  packages/components/src/Layout/Layout.tsx
  packages/components/src/Layout/README.md
  packages/components/src/Page/Page.tsx
  packages/components/src/Page/README.md
  packages/components/src/PageArea/PageArea.tsx
  packages/components/src/PageArea/README.md
  packages/components/src/PageContent/PageContent.tsx
  packages/components/src/PageContent/README.md
  packages/components/src/__tests__/__snapshots__/Button.test.tsx.snap
  packages/components/src/__tests__/__snapshots__/ButtonGroup.test.tsx.snap
  packages/components/src/__tests__/__snapshots__/Card.test.tsx.snap
  packages/components/src/__tests__/__snapshots__/Paginator.test.tsx.snap
  packages/components/src/__tests__/__snapshots__/Table.test.tsx.snap
  packages/theme/src/constants.ts
  packages/utils/src/styles.ts
Labels: Redesign, ✅ Can merge

#514 Enhance sidenav
  packages/components/src/Layout/Layout.tsx
  packages/components/src/Layout/README.md
  packages/components/src/Sidenav/README.md
  packages/components/src/Sidenav/Sidenav.tsx
  packages/components/src/SidenavHeader/README.md
  packages/components/src/SidenavHeader/SidenavHeader.tsx
  packages/components/src/SidenavItem/README.md
  packages/components/src/SidenavItem/SidenavItem.tsx
  packages/components/src/constants.ts
Labels: Redesign, ✅ Can merge

#513 Code component
  packages/components/package.json
  packages/components/src/Code/Code.tsx
  packages/components/src/Code/README.md
  packages/components/src/Code/styles.ts
  packages/components/src/__tests__/Code.test.tsx
  packages/components/src/__tests__/__snapshots__/Code.test.tsx.snap
  packages/components/src/index.ts
  packages/components/types/index.d.ts
  packages/website/src/Sections/Components/Codes.tsx
  packages/website/src/Sections/Components/index.ts
  yarn.lock
Labels: Redesign, ⚛️ components, ✅ Can merge

#524 Update Grid logic for Page
  package.json
  packages/components/src/Page/Page.tsx
  packages/components/src/Page/README.md
  packages/components/src/PageArea/PageArea.tsx
  packages/components/src/PageContent/PageContent.tsx
Labels: ✨ Enhancement

#530 Add a proper Form component
  packages/components/src/Form/Form.tsx
  packages/components/src/Form/README.md
  packages/components/src/index.ts
Labels: Redesign, ⚛️ components

#531 Replace xAttribute/yAttribute with series datum accessors.
  docs_legacy/visualizations/chart.md
  packages/visual-tests/src/TestCases/Chart/area-2.ts
  packages/visual-tests/src/TestCases/Chart/area-4.ts
  packages/visual-tests/src/TestCases/Chart/axes-6.ts
  packages/visual-tests/src/TestCases/Chart/bars-2.ts
  packages/visual-tests/src/TestCases/Chart/bars-4.ts
  packages/visual-tests/src/TestCases/Chart/range-2.ts
  packages/visual-tests/src/TestCases/Chart/range-4.ts
  packages/visual-tests/src/TestCases/Chart/symbol-2.ts
  packages/visual-tests/src/TestCases/Chart/symbol-3.ts
  packages/visualizations/src/Chart/facade.ts
  packages/visualizations/src/Chart/series/renderers/bars.ts
  packages/visualizations/src/Chart/series/series.ts
  packages/visualizations/src/Chart/series_manager.ts
  packages/visualizations/src/Chart/typings.ts
  packages/visualizations/types/fp.d.ts
Labels: visualizations

#533 Copy CNAME file to gh-pages deploys
  package.json
Labels: ✅ Can merge

#532 Close select when selecting single item
  packages/components/src/Select/README.md
  packages/components/src/Select/Select.tsx
Labels: ✅ Can merge

#538 Feature/input copy
  packages/components/package.json
  packages/components/src/Input/Input.tsx
  packages/components/src/Input/README.md
  yarn.lock
Labels: ✨ Enhancement
