Repository contiamo/operational-ui, pull requests merged in 2018-07, with the labels that each got.

#540 Fix layout on `<Layout/>`
  packages/components/src/Layout/Layout.tsx
  packages/components/src/Layout/README.md
Labels: ✅ Can merge

#544 Add custom icons
  packages/components/src/Breadcrumb/Breadcrumb.tsx
  packages/components/src/Button/Button.tsx
  packages/components/src/Button/README.md
  packages/components/src/Chip/README.md
  packages/components/src/ContextMenu/README.md
  packages/components/src/DatePicker/DatePicker.tsx
  packages/components/src/Icon/Icon.Custom.tsx
  packages/components/src/Icon/Icon.ReactFeather.ts
  packages/components/src/Icon/Icon.tsx
  packages/components/src/Icon/README.md
  packages/components/src/Input/Input.tsx
  packages/components/src/Message/Message.tsx
  packages/components/src/Progress/Progress.tsx
  packages/components/src/Select/Select.Option.tsx
  packages/components/src/Table/Table.tsx
  packages/components/src/Textarea/Textarea.tsx
  packages/components/src/__tests__/ContextMenu.test.tsx
  packages/components/src/__tests__/Icon.test.tsx
  packages/components/src/__tests__/__snapshots__/ContextMenu.test.tsx.snap
  packages/components/src/__tests__/__snapshots__/Icon.test.tsx.snap
  packages/components/src/__tests__/__snapshots__/Message.test.tsx.snap
Labels: ✅ Can merge

#548 Convert color constants to hex.
  packages/components/src/__tests__/__snapshots__/Button.test.tsx.snap
  packages/components/src/__tests__/__snapshots__/ButtonGroup.test.tsx.snap
  packages/components/src/__tests__/__snapshots__/Card.test.tsx.snap
  packages/components/src/__tests__/__snapshots__/Chip.test.tsx.snap
  packages/components/src/__tests__/__snapshots__/Input.test.tsx.snap
  packages/components/src/__tests__/__snapshots__/Paginator.test.tsx.snap
  packages/components/src/__tests__/__snapshots__/Select.test.tsx.snap
  packages/components/src/__tests__/__snapshots__/Table.test.tsx.snap
  packages/components/src/__tests__/__snapshots__/Tabs.test.tsx.snap
  packages/components/src/utils/constants.ts
Labels: ✅ Can merge

#549 Add opacity to chip backgrounds.
  packages/components/src/Chip/Chip.tsx
  packages/components/src/__tests__/__snapshots__/Chip.test.tsx.snap
  packages/components/src/utils/constants.ts
  packages/utils/src/__tests__/color.test.ts
  packages/utils/src/color.ts
Labels: ✅ Can merge

#551 Update component font weights with constants.
  packages/components/src/Breakdown/Breakdown.tsx
  packages/components/src/Button/Button.tsx
  packages/components/src/CardColumn/CardColumn.tsx
  packages/components/src/CardHeader/CardHeader.tsx
  packages/components/src/CardItem/CardItem.tsx
  packages/components/src/Chip/Chip.tsx
  packages/components/src/ContextMenu/ContextMenu.tsx
  packages/components/src/DatePicker/DatePicker.styles.ts
  packages/components/src/Grid/Grid.tsx
  packages/components/src/Messages/Messages.tsx
  packages/components/src/Page/Page.tsx
  packages/components/src/Select/Select.style.ts
  packages/components/src/SidenavHeader/SidenavHeader.tsx
  packages/components/src/SidenavItem/SidenavItem.tsx
  packages/components/src/Typography/Typography.tsx
  packages/components/src/utils/constants.ts
  packages/components/src/utils/mixins.ts
  packages/components/src/utils/with-label.tsx
Labels: ✅ Can merge

#550 Tooltip enhancements
  packages/components/src/Input/Input.tsx
  packages/components/src/Tooltip/README.md
  packages/components/src/Tooltip/Tooltip.Container.tsx
  packages/components/src/Tooltip/Tooltip.tsx
  packages/components/src/__tests__/__snapshots__/Tooltip.test.tsx.snap
  packages/components/src/utils/constants.ts
  packages/components/src/utils/mixins.ts
Labels: ✅ Can merge

#552 Update sidebar.
  packages/components/src/SidenavHeader/SidenavHeader.tsx
Labels: ✅ Can merge

#546 Message management inside OperationalUI
  packages/components/package.json
  packages/components/src/Breadcrumb/Breadcrumb.tsx
  packages/components/src/Button/Button.tsx
  packages/components/src/ContextMenu/ContextMenu.tsx
  packages/components/src/Message/Message.tsx
  packages/components/src/Messages/README.md
  packages/components/src/OperationalUI/OperationalUI.tsx
  packages/components/src/OperationalUI/README.md
  packages/components/src/SidenavHeader/SidenavHeader.tsx
  packages/components/src/SidenavItem/SidenavItem.tsx
  packages/components/src/Spinner/Spinner.tsx
  packages/components/src/Textarea/Textarea.tsx
  packages/components/src/__tests__/__snapshots__/Breadcrumbs.test.tsx.snap
  packages/components/src/__tests__/__snapshots__/Breakdown.test.tsx.snap
  packages/components/src/__tests__/__snapshots__/Button.test.tsx.snap
  packages/components/src/__tests__/__snapshots__/ButtonGroup.test.tsx.snap
  packages/components/src/__tests__/__snapshots__/Card.test.tsx.snap
  packages/components/src/__tests__/__snapshots__/Checkbox.test.tsx.snap
  packages/components/src/__tests__/__snapshots__/Chip.test.tsx.snap
  packages/components/src/__tests__/__snapshots__/Code.test.tsx.snap
  packages/components/src/__tests__/__snapshots__/ContextMenu.test.tsx.snap
  packages/components/src/__tests__/__snapshots__/Grid.test.tsx.snap
  packages/components/src/__tests__/__snapshots__/Header.test.tsx.snap
  packages/components/src/__tests__/__snapshots__/Icon.test.tsx.snap
  packages/components/src/__tests__/__snapshots__/Input.test.tsx.snap
  packages/components/src/__tests__/__snapshots__/Message.test.tsx.snap
  packages/components/src/__tests__/__snapshots__/Modal.test.tsx.snap
  packages/components/src/__tests__/__snapshots__/Paginator.test.tsx.snap
  packages/components/src/__tests__/__snapshots__/Progress.test.tsx.snap
  packages/components/src/__tests__/__snapshots__/Record.test.tsx.snap
  packages/components/src/__tests__/__snapshots__/Select.test.tsx.snap
  packages/components/src/__tests__/__snapshots__/Spinner.test.tsx.snap
  packages/components/src/__tests__/__snapshots__/Switch.test.tsx.snap
  packages/components/src/__tests__/__snapshots__/Table.test.tsx.snap
  packages/components/src/__tests__/__snapshots__/Tabs.test.tsx.snap
  packages/components/src/__tests__/__snapshots__/Tile.test.tsx.snap
  packages/components/src/__tests__/__snapshots__/Timeline.test.tsx.snap
  packages/components/src/__tests__/__snapshots__/Tooltip.test.tsx.snap
  packages/components/src/index.ts
  packages/components/src/types.ts
  packages/components/types/index.d.ts
  yarn.lock
Labels: ✅ Can merge

#556 NameTag component
  packages/components/src/Avatar/Avatar.tsx
  packages/components/src/Icon/Icon.tsx
  packages/components/src/NameTag/NameTag.tsx
  packages/components/src/NameTag/README.md
  packages/components/src/NameTag/__tests__/NameTag.test.tsx
  packages/components/src/NameTag/__tests__/__snapshots__/NameTag.test.tsx.snap
  packages/components/src/index.ts
Labels: ✅ Can merge

#555 Enhance spinner component
  packages/components/src/Icon/Icon.Custom.tsx
  packages/components/src/Spinner/README.md
  packages/components/src/Spinner/Spinner.tsx
Labels: ✅ Can merge

#559 Avatar and nametag color palette
  packages/components/src/Avatar/Avatar.tsx
  packages/components/src/utils/constants.ts
Labels: ✅ Can merge

#563 Enhance icons + add `Sql` and `SavedQuery` icon
  packages/components/src/Icon/Icon.Custom.tsx
Labels: ✅ Can merge

#570 Fix visualization color assigner.
  packages/visualizations/src/Chart/facade.ts
Labels: visualizations, ✅ Can merge

#569 Fix transform origin. Add left/right props
  packages/components/src/Spinner/Spinner.tsx
Labels: ✅ Can merge

#562 Hint component
  packages/components/src/Hint/Hint.tsx
  packages/components/src/Hint/README.md
  packages/components/src/Input/Input.tsx
  packages/components/src/Input/README.md
  packages/components/src/Textarea/README.md
  packages/components/src/Textarea/Textarea.tsx
  packages/components/src/Tooltip/Tooltip.Container.tsx
  packages/components/src/Tooltip/Tooltip.tsx
  packages/components/src/index.ts
  packages/components/src/utils/mixins.ts
Labels: ✅ Can merge

#577 Feat/confirm
  packages/components/src/Confirm/Confirm.tsx
  packages/components/src/Confirm/README.md
  packages/components/src/Internals/Overlay.tsx
  packages/components/src/Modal/Modal.tsx
  packages/components/src/PageArea/PageArea.tsx
  packages/components/src/utils/constants.ts
Labels: ✅ Can merge

#580 Export Confirm
  packages/components/src/__tests__/libExports.ts
  packages/components/src/index.ts
Labels: ✅ Can merge

#565 Add colorMapper util
  packages/components/src/Avatar/Avatar.tsx
  packages/components/src/NameTag/NameTag.tsx
  packages/components/src/NameTag/README.md
  packages/components/src/utils/__tests__/color.test.tsx
  packages/components/src/utils/color.ts
Labels: ✅ Can merge

#576 Remove utils package
  package.json
  packages/components/package.json
  packages/components/src/Avatar/Avatar.tsx
  packages/components/src/Breadcrumb/Breadcrumb.tsx
  packages/components/src/Breakdown/Breakdown.tsx
  packages/components/src/Button/Button.tsx
  packages/components/src/ContextMenu/ContextMenu.tsx
  packages/components/src/ContextMenuItem/ContextMenuItem.tsx
  packages/components/src/DatePicker/DatePicker.styles.ts
  packages/components/src/NameTag/NameTag.tsx
  packages/components/src/OperationalUI/OperationalUI.tsx
  packages/components/src/Progress/Progress.tsx
  packages/components/src/Select/Select.Filter.tsx
  packages/components/src/Select/Select.Option.tsx
  packages/components/src/Select/Select.style.ts
  packages/components/src/Select/Select.tsx
  packages/components/src/Sidenav/Sidenav.tsx
  packages/components/src/SidenavHeader/SidenavHeader.tsx
  packages/components/src/Tabs/Tabs.tsx
  packages/components/src/Textarea/Textarea.tsx
  packages/components/src/Tile/Tile.tsx
  packages/components/src/utils/__tests__/color.test.ts
  packages/components/src/utils/__tests__/index.test.ts
  packages/components/src/utils/color.ts
  packages/components/src/utils/constants/deprecatedTheme.ts
  packages/components/src/utils/index.ts
  packages/components/src/utils/mixins.ts
  packages/utils/README.md
  packages/utils/package.json
  packages/utils/src/__tests__/d3.test.ts
  packages/utils/src/d3.ts
  packages/utils/src/index.ts
  packages/utils/src/styles.ts
  packages/utils/src/text.ts
  packages/utils/tsconfig.json
  packages/utils/types/index.d.ts
  packages/visual-tests/package.json
  packages/visual-tests/src/App.tsx
  packages/visualizations/package.json
  packages/visualizations/scripts/dev-server/site_chart.tsx
  packages/visualizations/scripts/dev-server/site_pie_chart.tsx
  packages/visualizations/scripts/dev-server/site_process_flow.tsx
  packages/visualizations/src/Chart/facade.ts
  packages/visualizations/src/PieChart/renderers/renderer_utils.ts
  packages/visualizations/src/ProcessFlow/styles.ts
  packages/visualizations/src/Sunburst/breadcrumb.ts
  packages/visualizations/src/Sunburst/facade.ts
  packages/visualizations/src/utils/color.ts
  packages/visualizations/src/utils/colorAssigner.ts
  yarn.lock
Labels: ✅ Can merge

#586 Re-add href attribute to Button component
  packages/components/src/Button/Button.tsx
Labels: ✅ Can merge

#582 Add a pull request template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: Discussion, help wanted

#566 HeaderMenu
  packages/components/src/Breadcrumbs/README.md
  packages/components/src/ContextMenu/ContextMenu.Item.tsx
  packages/components/src/ContextMenu/ContextMenu.tsx
  packages/components/src/ContextMenu/README.md
  packages/components/src/ContextMenu/__tests__/ContextMenu.test.tsx
  packages/components/src/ContextMenu/__tests__/__snapshots__/ContextMenu.test.tsx.snap
  packages/components/src/ContextMenuItem/ContextMenuItem.tsx
  packages/components/src/DatePicker/DatePicker.styles.ts
  packages/components/src/HeaderMenu/HeaderMenu.tsx
  packages/components/src/HeaderMenu/README.md
  packages/components/src/Page/README.md
  packages/components/src/Select/Select.style.ts
  packages/components/src/Select/Select.tsx
  packages/components/src/SidenavHeader/SidenavHeader.tsx
  packages/components/src/index.ts
  packages/components/src/utils/constants.ts
  packages/components/src/utils/mixins.ts
Labels: ⚛️ components, ✅ Can merge

#588 Add visual tests for adding series and updating palettes.
  packages/visualizations/src/Chart/facade.ts
  packages/visualizations/src/Chart/series_manager.ts
  packages/visualizations/src/PieChart/facade.ts
  packages/visualizations/src/Sunburst/facade.ts
  packages/visualizations/src/utils/VisualizationWrapper.tsx
  packages/visualizations/src/utils/theme.ts
  packages/visualizations/visual-tests/TestCases/Chart/bars-5.ts
  packages/visualizations/visual-tests/TestCases/Chart/bars-6.ts
  packages/visualizations/visual-tests/TestCases/Chart/index.ts
  packages/visualizations/visual-tests/TestCases/Chart/lines-1.ts
  packages/visualizations/visual-tests/TestCases/Chart/lines-2.ts
  packages/visualizations/visual-tests/TestCases/Chart/symbol-4.ts
Labels: visualizations, ✅ Can merge

#593 Remove deprecated theme from visualizations.
  packages/visualizations/src/Chart/axes/styles.ts
  packages/visualizations/src/Chart/facade.ts
  packages/visualizations/src/Chart/focus/styles.ts
  packages/visualizations/src/Chart/series/renderers/styles.ts
  packages/visualizations/src/Chart/styles.ts
  packages/visualizations/src/PieChart/facade.ts
  packages/visualizations/src/PieChart/renderers/styles.ts
  packages/visualizations/src/ProcessFlow/styles.ts
  packages/visualizations/src/Sunburst/facade.ts
  packages/visualizations/src/Sunburst/styles.ts
  packages/visualizations/src/shared/styles.ts
  packages/visualizations/src/utils/VisualizationWrapper.tsx
  packages/visualizations/src/utils/constants.ts
Labels: visualizations, ✅ Can merge

#579 Replace webpack with file-by-file tsc build for components
  packages/components/package.json
  packages/components/src/utils/__tests__/color.test.ts
  packages/components/src/utils/__tests__/color.test.tsx
Labels: ✅ Can merge

#596 Feat/textarea fullwidth
  packages/components/src/CardColumn/CardColumn.tsx
  packages/components/src/CardColumns/README.md
  packages/components/src/Code/Code.tsx
  packages/components/src/ContextMenu/ContextMenu.tsx
  packages/components/src/Textarea/Textarea.tsx
  packages/components/src/utils/with-label.tsx
Labels: ⚛️ components

#594 Date picker min-max ranges and visual updates
  packages/components/src/DatePicker/DatePicker.Month.tsx
  packages/components/src/DatePicker/DatePicker.styles.ts
  packages/components/src/DatePicker/DatePicker.tsx
  packages/components/src/DatePicker/DatePicker.utils.ts
  packages/components/src/DatePicker/README.md
  packages/components/src/DatePicker/__tests__/DatePicker.test.tsx
  packages/components/src/DatePicker/__tests__/__snapshots__/DatePicker.test.tsx.snap
Labels: ✅ Can merge

#607 Fix vertical alignment bug for card header action items
  packages/components/src/CardHeader/CardHeader.tsx
  packages/components/src/CardHeader/README.md
Labels: ✅ Can merge

#612 Hidden tab
  packages/components/src/Page/Page.tsx
  packages/components/src/Page/README.md
Labels: ✨ Enhancement

#604 ProgressPanel component
  packages/components/src/Button/__tests__/Button.test.tsx
  packages/components/src/Button/__tests__/__snapshots__/Button.test.tsx.snap
  packages/components/src/Icon/Icon.Custom.tsx
  packages/components/src/Icon/Icon.tsx
  packages/components/src/ProgressPanel/ProgressPanel.tsx
  packages/components/src/ProgressPanel/README.md
  packages/components/src/ProgressPanel/__tests__/ProgressPanel.test.tsx
  packages/components/src/ProgressPanel/__tests__/__snapshots__/ProgressPanel.test.tsx.snap
  packages/components/src/index.ts
Labels: ✅ Can merge

#613 Add PageAreas for advanced layout cases
  packages/components/src/PageAreas/PageAreas.tsx
  packages/components/src/PageAreas/README.md
  packages/components/src/index.ts
Labels: ⚛️ components, ✨ Enhancement

#614 Improve status api
  packages/components/src/Status/README.md
  packages/components/src/Status/Status.tsx
Labels: ✨ Enhancement

#616 Enhance/new contiamo logo
  packages/components/src/ContiamoLogo/ContiamoLogo.tsx
  packages/components/src/ContiamoLogo/README.md
  packages/components/src/HeaderBar/HeaderBar.tsx
Labels: ✅ Can merge

#611 Add tree component
  packages/components/src/Internals/SmallNameTag.tsx
  packages/components/src/Tree/README.md
  packages/components/src/Tree/Tree.tsx
  packages/components/src/Tree/Tree.types.ts
  packages/components/src/Tree/Tree.utils.ts
  packages/components/src/Tree/__tests__/Tree.test.tsx
  packages/components/src/Tree/__tests__/__snapshots__/Tree.test.tsx.snap
  packages/components/src/index.ts
Labels: ✅ Can merge

#618 Add aliases to ProgressPanel to match more usages
  packages/components/src/ProgressPanel/ProgressPanel.tsx
  packages/components/src/ProgressPanel/README.md
  packages/components/src/ResourceName/ResourceName.tsx
Labels: ✨ Enhancement

#619 Explicit overflow on sidenav header
  packages/components/src/Sidenav/README.md
  packages/components/src/Sidenav/Sidenav.tsx
Labels: ✅ Can merge

#617 Redesign Textarea component.
  packages/components/src/Textarea/README.md
  packages/components/src/Textarea/Textarea.tsx
  packages/components/src/utils/mixins.ts
Labels: ✅ Can merge

#621 Strict logo sizing inside header bar
  packages/components/src/ContiamoLogo/ContiamoLogo.tsx
  packages/components/src/HeaderBar/HeaderBar.tsx
  packages/components/src/HeaderBar/README.md
Labels: ✅ Can merge

#623 Fix layout main overflow
  packages/components/src/Layout/Layout.tsx
Labels: ✅ Can merge

#625 Generalized logo component
  packages/components/src/ContiamoLogo/ContiamoLogo.tsx
  packages/components/src/ContiamoLogo/README.md
  packages/components/src/HeaderBar/README.md
  packages/components/src/HeaderMenu/README.md
  packages/components/src/Layout/README.md
  packages/components/src/Logo/Logo.Shapes.tsx
  packages/components/src/Logo/Logo.tsx
  packages/components/src/Logo/README.md
  packages/components/src/index.ts
Labels: ✅ Can merge

#624 Add confirm and modal to the Page component as function-as-a-child
  packages/components/src/Card/Card.test.tsx
  packages/components/src/Card/__tests__/Card.test.tsx
  packages/components/src/Card/__tests__/__snapshots__/Card.test.tsx.snap
  packages/components/src/Confirm/Confirm.tsx
  packages/components/src/Confirm/README.md
  packages/components/src/Internals/ControlledModal.tsx
  packages/components/src/Layout/README.md
  packages/components/src/Modal/Modal.tsx
  packages/components/src/Modal/README.md
  packages/components/src/OperationalUI/README.md
  packages/components/src/Page/Page.tsx
  packages/components/src/Page/README.md
  packages/components/src/index.ts
Labels: ✅ Can merge

#634 Update package.json to include built assets
  package.json
Labels: priority

#636 Spread html props for AvatarGroup
  src/AvatarGroup/AvatarGroup.tsx
Labels: can merge

#633 BREAKING: Allow only react elements in page tabs
  src/Page/Page.tsx
  src/Page/README.md
  src/Tab/README.md
  src/Tab/Tab.tsx
  src/index.ts
Labels: blocker, can merge

#637 Spread HTML props for Breadcrumb
  src/Breadcrumb/Breadcrumb.tsx
Labels: can merge

#638 Spread HTML props for Breadcrumbs
  src/Breadcrumbs/Breadcrumbs.tsx
  styleguide.config.js
Labels: can merge

#640 Spread HTML props for low-risk components
  src/Breakdown/Breakdown.tsx
  src/Chip/Chip.tsx
  src/Chip/__tests__/Chip.test.tsx
  src/Chip/__tests__/__snapshots__/Chip.test.tsx.snap
  src/Code/Code.tsx
  src/Code/__tests__/Code.test.tsx
  src/Code/__tests__/__snapshots__/Code.test.tsx.snap
  src/Grid/Grid.tsx
  src/Message/Message.tsx
  src/Messages/Messages.tsx
  src/Paginator/Paginator.tsx
  src/Progress/Progress.tsx
  src/ProgressPanel/ProgressPanel.tsx
  src/Sha/Sha.tsx
  src/Switch/Switch.tsx
  src/Table/Table.tsx
  src/Tree/Tree.tsx
Labels: can merge

#631 BREAKING: Simplify Loading Progress & Add to Context
  package.json
  src/Breadcrumb/Breadcrumb.tsx
  src/Breadcrumbs/__tests__/__snapshots__/Breadcrumbs.test.tsx.snap
  src/Breakdown/__tests__/__snapshots__/Breakdown.test.tsx.snap
  src/Button/Button.tsx
  src/Button/__tests__/__snapshots__/Button.test.tsx.snap
  src/Card/__tests__/__snapshots__/Card.test.tsx.snap
  src/Chip/__tests__/__snapshots__/Chip.test.tsx.snap
  src/Code/__tests__/__snapshots__/Code.test.tsx.snap
  src/ContextMenu/__tests__/__snapshots__/ContextMenu.test.tsx.snap
  src/DatePicker/__tests__/__snapshots__/DatePicker.test.tsx.snap
  src/Grid/__tests__/__snapshots__/Grid.test.tsx.snap
  src/Icon/__tests__/__snapshots__/Icon.test.tsx.snap
  src/Logo/Logo.tsx
  src/Message/__tests__/__snapshots__/Message.test.tsx.snap
  src/NameTag/__tests__/__snapshots__/NameTag.test.tsx.snap
  src/OperationalContext/OperationalContext.init.tsx
  src/OperationalContext/OperationalContext.tsx
  src/OperationalContext/README.md
  src/OperationalUI/OperationalUI.tsx
  src/OperationalUI/README.md
  src/Paginator/__tests__/__snapshots__/Paginator.test.tsx.snap
  src/Progress/__tests__/__snapshots__/Progress.test.tsx.snap
  src/ProgressPanel/__tests__/__snapshots__/ProgressPanel.test.tsx.snap
  src/Select/__tests__/__snapshots__/Select.test.tsx.snap
  src/SidenavHeader/SidenavHeader.tsx
  src/SidenavItem/SidenavItem.tsx
  src/Spinner/__tests__/__snapshots__/Spinner.test.tsx.snap
  src/Switch/__tests__/__snapshots__/Switch.test.tsx.snap
  src/Table/__tests__/__snapshots__/Table.test.tsx.snap
  src/Tooltip/Tooltip.Container.tsx
  src/Tooltip/Tooltip.tsx
  src/Tooltip/__tests__/__snapshots__/Tooltip.test.tsx.snap
  src/Tree/__tests__/__snapshots__/Tree.test.tsx.snap
  src/index.ts
  src/utils/mixins.ts
  styleguide/StyleGuideRenderer.tsx
  styleguide/Wrapper.tsx
  yarn.lock
Labels: can merge

#643 Spread HTML props one more batch of components
  src/ActionMenu/ActionMenu.tsx
  src/Avatar/Avatar.tsx
  src/AvatarGroup/AvatarGroup.tsx
  src/Breadcrumb/Breadcrumb.tsx
  src/Breadcrumbs/Breadcrumbs.tsx
  src/Breakdown/Breakdown.tsx
  src/Button/Button.tsx
  src/ButtonGroup/ButtonGroup.tsx
  src/ButtonGroup/__tests__/ButtonGroup.test.tsx
  src/ButtonGroup/__tests__/__snapshots__/ButtonGroup.test.tsx.snap
  src/Card/Card.tsx
  src/CardColumn/CardColumn.tsx
  src/CardHeader/CardHeader.tsx
  src/CardItem/CardItem.tsx
  src/Chip/Chip.tsx
  src/Code/Code.tsx
  src/ContextMenu/ContextMenu.tsx
  src/DatePicker/DatePicker.tsx
  src/Grid/Grid.tsx
  src/HeaderBar/HeaderBar.tsx
  src/HeaderMenu/HeaderMenu.tsx
  src/Hint/Hint.tsx
  src/Input/Input.tsx
  src/Layout/Layout.tsx
  src/Logo/Logo.tsx
  src/Message/Message.tsx
  src/Messages/Messages.tsx
  src/NameTag/NameTag.tsx
  src/OperationalContext/OperationalContext.tsx
  src/Page/Page.tsx
  src/PageArea/PageArea.tsx
  src/PageAreas/PageAreas.tsx
  src/PageContent/PageContent.tsx
  src/Paginator/Paginator.tsx
  src/Progress/Progress.tsx
  src/ProgressPanel/ProgressPanel.tsx
  src/Select/Select.tsx
  src/Sidenav/Sidenav.tsx
  src/SidenavHeader/SidenavHeader.tsx
  src/SidenavItem/SidenavItem.tsx
  src/Spinner/Spinner.tsx
  src/Status/Status.tsx
  src/Switch/Switch.tsx
  src/Table/Table.tsx
  src/Textarea/Textarea.tsx
  src/Tooltip/Tooltip.tsx
  src/Tree/Tree.tsx
  src/__tests__/libExports.ts
  src/types.ts
Labels: can merge

#646 Spread HTML props for input components
  src/DatePicker/DatePicker.tsx
  src/Input/Input.tsx
  src/Select/Select.Option.tsx
  src/Select/Select.tsx
  src/Select/__tests__/__snapshots__/Select.test.tsx.snap
Labels: can merge
