Repository contiamo/operational-ui, pull requests merged in 2018-08, with the labels that each got.

#648 Remove non-HTML attributes from Page component props spread
  src/Page/Page.tsx
Labels: can merge

#653 Add InfoPanel component
  src/InfoPanel/InfoPanel.tsx
  src/InfoPanel/README.md
  src/index.ts
Labels: ✨ enhancement

#652 Export type definitions
  src/ActionMenu/ActionMenu.tsx
  src/Avatar/Avatar.tsx
  src/AvatarGroup/AvatarGroup.tsx
  src/Breadcrumb/Breadcrumb.tsx
  src/Breadcrumbs/Breadcrumbs.tsx
  src/Breakdown/Breakdown.tsx
  src/Button/Button.tsx
  src/ButtonGroup/ButtonGroup.tsx
  src/Card/Card.tsx
  src/CardColumn/CardColumn.tsx
  src/CardHeader/CardHeader.tsx
  src/CardItem/CardItem.tsx
  src/Chip/Chip.tsx
  src/Code/Code.tsx
  src/ContextMenu/ContextMenu.tsx
  src/DatePicker/DatePicker.tsx
  src/Grid/Grid.tsx
  src/HeaderBar/HeaderBar.tsx
  src/HeaderMenu/HeaderMenu.tsx
  src/Hint/Hint.tsx
  src/Icon/Icon.Brand.tsx
  src/Icon/Icon.tsx
  src/Input/Input.tsx
  src/Internals/Confirm.tsx
  src/Internals/ControlledModal.tsx
  src/Layout/Layout.tsx
  src/Logo/Logo.tsx
  src/Message/Message.tsx
  src/Messages/Messages.tsx
  src/NameTag/NameTag.tsx
  src/OperationalUI/OperationalUI.tsx
  src/PageAreas/PageAreas.tsx
  src/Paginator/Paginator.tsx
  src/Progress/Progress.tsx
  src/ProgressPanel/ProgressPanel.tsx
  src/Select/Select.tsx
  src/Sidenav/Sidenav.tsx
  src/SidenavHeader/SidenavHeader.tsx
  src/SidenavItem/SidenavItem.tsx
  src/Spinner/Spinner.tsx
  src/Status/Status.tsx
  src/Switch/Switch.tsx
  src/Table/Table.tsx
  src/Textarea/Textarea.tsx
  src/Tree/Tree.tsx
  src/index.ts
Labels: can merge

#649 Spread HTML props for remaining components
  src/DatePicker/DatePicker.tsx
  src/HeaderBar/HeaderBar.tsx
  src/Layout/Layout.tsx
  src/NameTag/NameTag.tsx
  src/NameTag/__tests__/__snapshots__/NameTag.test.tsx.snap
  src/PageAreas/PageAreas.tsx
Labels: can merge

#647 Feature: Splash Screen
  src/Internals/ErrorBoundary.tsx
  src/OperationalUI/OperationalUI.tsx
  src/Splash/README.md
  src/Splash/Splash.Animation.tsx
  src/Splash/Splash.Logo.tsx
  src/Splash/Splash.tsx
  src/index.ts
  styleguide/StyleGuideRenderer.tsx
Labels: can merge

#654 Improve confirm api
  package.json
  src/CardColumn/CardColumn.tsx
  src/Internals/Confirm.tsx
  src/Internals/ControlledModal.tsx
  src/Internals/Modal.tsx
  src/Page/README.md
  src/Splash/Splash.Animation.tsx
  src/Typography/Body.tsx
  src/Typography/FinePrint.tsx
  src/index.ts
  styleguide/StyleGuideRenderer.tsx
  yarn.lock
Labels: can merge, ✨ enhancement

#658 Workaround compiled `.d.ts` files
  package.json
  src/DatePicker/DatePicker.styles.ts
  src/Form/Form.tsx
  src/Internals/Overlay.tsx
  src/OperationalUI/OperationalUI.tsx
  src/PageArea/PageArea.tsx
  src/ResourceName/ResourceName.tsx
  src/Select/Select.style.ts
  src/Tooltip/Tooltip.Container.tsx
  src/Typography/Body.tsx
  src/Typography/FinePrint.tsx
  src/Typography/Small.tsx
  src/Typography/Title.tsx
  src/utils/constants.ts
  src/utils/mixins.ts
  tsconfig.json
Labels: can merge

#681 **Feature: ** Deterministic ordering for card items
  src/Card/Card.tsx
Labels: can merge

#675 **Breaking: ** Add `CardSection` component
  dev-server/index.html
  dev-server/index.tsx
  package.json
  src/Card/Card.tsx
  src/Card/__tests__/__snapshots__/Card.test.tsx.snap
  src/CardHeader/CardHeader.tsx
  src/CardSection/CardSection.tsx
  src/CardSection/README.md
  src/Tree/Tree.tsx
  src/Tree/Tree.types.ts
  src/index.ts
  src/types.ts
  styleguide/SectionHeadingRenderer.tsx
  yarn.lock
Labels: can merge

#680 **Feature: ** Add condensedTitle option to Page component.
  src/Page/Page.tsx
  src/Page/README.md
Labels: can merge
