Repository contiamo/operational-ui, pull requests merged in 2018-03, with the labels that each got.

#329 Refactor pie chart accessors, add color assigner.
  packages/showcase/components/TestCases/PieChart/Donut/case01.js
  packages/showcase/components/TestCases/PieChart/Donut/case02.js
  packages/showcase/components/TestCases/PieChart/Gauge/case01.js
  packages/showcase/components/TestCases/PieChart/Gauge/case02.js
  packages/showcase/components/TestCases/PieChart/Gauge/case03.js
  packages/showcase/components/TestCases/PieChart/Gauge/case04.js
  packages/showcase/components/TestCases/PieChart/Gauge/case05.js
  packages/showcase/components/TestCases/PieChart/Gauge/case06.js
  packages/showcase/components/TestCases/PieChart/Gauge/case07.js
  packages/showcase/components/TestCases/PieChart/Polar/case01.js
  packages/showcase/components/TestCases/PieChart/Polar/case02.js
  packages/showcase/components/TestCases/PieChart/case01.js
  packages/showcase/components/TestCases/PieChart/case02.js
  packages/showcase/components/TestCases/PieChart/case03.js
  packages/visualizations/lib/PieChart/facade.js
  packages/visualizations/lib/PieChart/facade.js.map
  packages/visualizations/lib/PieChart/focus.d.ts
  packages/visualizations/lib/PieChart/focus.js
  packages/visualizations/lib/PieChart/focus.js.map
  packages/visualizations/lib/PieChart/renderers/abstract_renderer.d.ts
  packages/visualizations/lib/PieChart/renderers/abstract_renderer.js
  packages/visualizations/lib/PieChart/renderers/abstract_renderer.js.map
  packages/visualizations/lib/PieChart/renderers/gauge.js
  packages/visualizations/lib/PieChart/renderers/gauge.js.map
  packages/visualizations/lib/PieChart/renderers/polar.js
  packages/visualizations/lib/PieChart/renderers/polar.js.map
  packages/visualizations/lib/PieChart/typings.d.ts
  packages/visualizations/scripts/dev-server/index.js
  packages/visualizations/scripts/dev-server/site_pie_chart.tsx
  packages/visualizations/src/PieChart/facade.ts
  packages/visualizations/src/PieChart/focus.ts
  packages/visualizations/src/PieChart/renderers/abstract_renderer.ts
  packages/visualizations/src/PieChart/renderers/gauge.ts
  packages/visualizations/src/PieChart/renderers/polar.ts
  packages/visualizations/src/PieChart/typings.ts
Labels: visualizations, ✅ Can merge

#338 Simplify build scripts. Tests on CI
  package.json
  packages/blocks/package.json
  packages/components/package.json
  packages/theme/package.json
  packages/utils/package.json
  packages/visualizations/package.json
  scripts/add-build-scripts.js
Labels: ✅ Can merge

#342 Simple idiomatic input
  packages/components/lib/Input.d.ts
  packages/components/lib/Input.js
  packages/components/lib/Input.js.map
  packages/components/lib/utils/mixins.d.ts
  packages/components/lib/utils/mixins.js
  packages/components/lib/utils/mixins.js.map
  packages/components/scripts/dev-server/site.tsx
  packages/components/src/Input.tsx
  packages/components/src/__tests__/__snapshots__/Input.test.tsx.snap
  packages/components/src/utils/mixins.ts
  packages/showcase/pages/components/form-fields.js
  packages/visualizations/package.json
Labels: ✅ Can merge

#341 Add automatic node label positioning to process flow.
  packages/showcase/pages/visualizations/process-flow/index.js
  packages/visualizations/lib/ProcessFlow/facade.js
  packages/visualizations/lib/ProcessFlow/facade.js.map
  packages/visualizations/lib/ProcessFlow/renderers/nodes.d.ts
  packages/visualizations/lib/ProcessFlow/renderers/nodes.js
  packages/visualizations/lib/ProcessFlow/renderers/nodes.js.map
  packages/visualizations/scripts/dev-server/index.js
  packages/visualizations/scripts/dev-server/site_process_flow.tsx
  packages/visualizations/src/ProcessFlow/facade.ts
  packages/visualizations/src/ProcessFlow/renderers/nodes.ts
Labels: visualizations

#339 Fix pie chart percentage string.
  packages/visualizations/lib/PieChart/renderers/abstract_renderer.js
  packages/visualizations/lib/PieChart/renderers/abstract_renderer.js.map
  packages/visualizations/src/PieChart/renderers/abstract_renderer.ts
Labels: visualizations

#345 Date picker fixes
  packages/components/lib/DatePicker.js
  packages/components/lib/DatePicker.js.map
  packages/components/lib/DatePicker/DatePicker.styles.js
  packages/components/lib/DatePicker/DatePicker.styles.js.map
  packages/components/src/DatePicker.tsx
  packages/components/src/DatePicker/DatePicker.styles.ts
Labels: ✅ Can merge

#350 Layout component
  packages/components/lib/Header.js
  packages/components/lib/Header.js.map
  packages/components/lib/Layout.d.ts
  packages/components/lib/Layout.js
  packages/components/lib/Layout.js.map
  packages/components/lib/Sidenav.d.ts
  packages/components/lib/Sidenav.js
  packages/components/lib/Sidenav.js.map
  packages/components/lib/SidenavHeader.js
  packages/components/lib/SidenavHeader.js.map
  packages/components/lib/SidenavItem.js
  packages/components/lib/SidenavItem.js.map
  packages/components/lib/constants.d.ts
  packages/components/lib/constants.js
  packages/components/lib/constants.js.map
  packages/components/lib/index.d.ts
  packages/components/lib/index.js
  packages/components/lib/index.js.map
  packages/components/scripts/dev-server/site.tsx
  packages/components/src/Header.tsx
  packages/components/src/Layout.tsx
  packages/components/src/Sidenav.tsx
  packages/components/src/SidenavHeader.tsx
  packages/components/src/SidenavItem.tsx
  packages/components/src/__tests__/__snapshots__/Header.test.tsx.snap
  packages/components/src/constants.ts
  packages/components/src/index.ts
  packages/showcase/components/Layout.js
  packages/showcase/pages/_document.js
  packages/showcase/pages/getting-started.js
  packages/utils/lib/styles.js
  packages/utils/lib/styles.js.map
  packages/utils/src/styles.ts
Labels: ✅ Can merge

#359 Add icon and progress errors to Auth block. Progress tweaks
  packages/blocks/lib/Auth.d.ts
  packages/blocks/lib/Auth.js
  packages/blocks/lib/Auth.js.map
  packages/blocks/scripts/dev-server/site.tsx
  packages/blocks/src/Auth.tsx
  packages/components/lib/Progress.js
  packages/components/lib/Progress.js.map
  packages/components/src/Progress.tsx
  packages/components/src/__tests__/__snapshots__/Progress.test.tsx.snap
  packages/visualizations/package.json
  yarn.lock
Labels: ✅ Can merge

#363 Enable empty segments in sunburst charts.
  packages/visualizations/lib/Sunburst/breadcrumb.js
  packages/visualizations/lib/Sunburst/breadcrumb.js.map
  packages/visualizations/lib/Sunburst/data_handler.js
  packages/visualizations/lib/Sunburst/data_handler.js.map
  packages/visualizations/lib/Sunburst/renderer.d.ts
  packages/visualizations/lib/Sunburst/renderer.js
  packages/visualizations/lib/Sunburst/renderer.js.map
  packages/visualizations/lib/Sunburst/styles.js
  packages/visualizations/lib/Sunburst/styles.js.map
  packages/visualizations/lib/Sunburst/typings.d.ts
  packages/visualizations/scripts/dev-server/index.js
  packages/visualizations/scripts/dev-server/site_sunburst.tsx
  packages/visualizations/src/Sunburst/breadcrumb.ts
  packages/visualizations/src/Sunburst/data_handler.ts
  packages/visualizations/src/Sunburst/renderer.ts
  packages/visualizations/src/Sunburst/styles.ts
  packages/visualizations/src/Sunburst/typings.ts
Labels: visualizations

#364 Improve general styling
  packages/components/lib/Button.js
  packages/components/lib/Button.js.map
  packages/components/lib/Card.js
  packages/components/lib/Card.js.map
  packages/components/lib/CardHeader.js
  packages/components/lib/CardHeader.js.map
  packages/components/lib/Grid.js
  packages/components/lib/Grid.js.map
  packages/components/lib/Header.js
  packages/components/lib/Header.js.map
  packages/components/lib/Input.js
  packages/components/lib/Select.d.ts
  packages/components/lib/Select.js
  packages/components/lib/Select.js.map
  packages/components/lib/Select/Select.style.js
  packages/components/lib/Select/Select.style.js.map
  packages/components/lib/Switch.js
  packages/components/lib/Switch.js.map
  packages/components/lib/constants.js
  packages/components/lib/utils/mixins.js
  packages/components/lib/utils/mixins.js.map
  packages/components/scripts/dev-server/site.tsx
  packages/components/src/Button.tsx
  packages/components/src/Card.tsx
  packages/components/src/CardHeader.tsx
  packages/components/src/Grid.tsx
  packages/components/src/Header.tsx
  packages/components/src/Input.tsx
  packages/components/src/Select.tsx
  packages/components/src/Select/Select.style.ts
  packages/components/src/Switch.tsx
  packages/components/src/__tests__/__snapshots__/Button.test.tsx.snap
  packages/components/src/__tests__/__snapshots__/ButtonGroup.test.tsx.snap
  packages/components/src/__tests__/__snapshots__/Card.test.tsx.snap
  packages/components/src/__tests__/__snapshots__/ColorPicker.test.tsx.snap
  packages/components/src/__tests__/__snapshots__/Grid.test.tsx.snap
  packages/components/src/__tests__/__snapshots__/Header.test.tsx.snap
  packages/components/src/__tests__/__snapshots__/Input.test.tsx.snap
  packages/components/src/__tests__/__snapshots__/Paginator.test.tsx.snap
  packages/components/src/__tests__/__snapshots__/Record.test.tsx.snap
  packages/components/src/__tests__/__snapshots__/Select.test.tsx.snap
  packages/components/src/__tests__/__snapshots__/Sidenav.test.tsx.snap
  packages/components/src/__tests__/__snapshots__/Switch.test.tsx.snap
  packages/components/src/constants.ts
  packages/components/src/utils/mixins.ts
  packages/theme/lib/index.js
  packages/theme/src/index.ts
Labels: ✅ Can merge
