Repository contiamo/operational-ui, pull requests merged in 2018-05, with the labels that each got.

#423 Fix missing css runtime error in textarea
  packages/components/lib/Breadcrumbs.js
  packages/components/lib/Breadcrumbs.js.map
  packages/components/lib/Textarea.js
  packages/components/lib/Textarea.js.map
  packages/components/src/Textarea.tsx
Labels: ✅ Can merge

#425 Page styling
  packages/components/lib/Breadcrumbs.js
  packages/components/lib/Breadcrumbs.js.map
  packages/components/lib/Layout.js
  packages/components/lib/Layout.js.map
  packages/components/lib/Page.d.ts
  packages/components/lib/Page.js
  packages/components/lib/Page.js.map
  packages/components/scripts/dev-server/Explore.tsx
  packages/components/src/Breadcrumbs.tsx
  packages/components/src/Layout.tsx
  packages/components/src/Page.tsx
  packages/components/src/__tests__/__snapshots__/Breadcrumbs.test.tsx.snap
Labels: ✅ Can merge

#426 Table actions and column css
  packages/components/lib/Table.d.ts
  packages/components/lib/Table.js
  packages/components/lib/Table.js.map
  packages/components/scripts/dev-server/Explore.tsx
  packages/components/src/Table.tsx
  packages/components/src/__tests__/__snapshots__/Table.test.tsx.snap
Labels: ✅ Can merge

#427 Dev environments to parcel
  .gitignore
  packages/blocks/.gitignore
  packages/blocks/package.json
  packages/blocks/scripts/dev-server/index.html
  packages/blocks/scripts/dev-server/index.js
  packages/blocks/scripts/dev-server/index.tsx
  packages/components/.gitignore
  packages/components/lib/Table.js
  packages/components/lib/Table.js.map
  packages/components/package.json
  packages/components/scripts/dev-server/index.html
  packages/components/scripts/dev-server/index.js
  packages/components/scripts/dev-server/index.tsx
  packages/components/scripts/dev-server/site.tsx
  packages/visualizations/.gitignore
  packages/visualizations/package.json
  packages/visualizations/scripts/dev-server/index.html
  packages/visualizations/scripts/dev-server/index.js
  packages/visualizations/scripts/dev-server/site_pie_chart.tsx
  packages/visualizations/scripts/dev-server/site_process_flow.tsx
  packages/visualizations/scripts/dev-server/site_sunburst.tsx
  packages/website/.gitignore
  yarn.lock
Labels: ✅ Can merge

#428 Disable link default styling in side nav
  packages/components/lib/Sidenav.js
  packages/components/lib/Sidenav.js.map
  packages/components/scripts/dev-server/index.tsx
  packages/components/src/Sidenav.tsx
Labels: ✅ Can merge

#430 Fix visual tests build
  packages/visual-tests/package.json
  packages/visual-tests/src/App.tsx
  packages/visual-tests/src/TestCases/ProcessFlow/case04.ts
  yarn.lock
Labels: ✅ Can merge

#429 Sidenav gradient
  packages/components/lib/Sidenav.js
  packages/components/lib/Sidenav.js.map
  packages/components/src/Sidenav.tsx
  scripts/ci.sh
Labels: ✅ Can merge

#435 Parcel builds for website and visual tests
  packages/visual-tests/package.json
  packages/visual-tests/src/index.html
  packages/website/package.json
  packages/website/public/index.html
  packages/website/src/components/StaticContent.tsx
  packages/website/src/favicons/__original.png
  packages/website/src/favicons/android-icon-144x144.png
  packages/website/src/favicons/android-icon-192x192.png
  packages/website/src/favicons/android-icon-36x36.png
  packages/website/src/favicons/android-icon-48x48.png
  packages/website/src/favicons/android-icon-72x72.png
  packages/website/src/favicons/android-icon-96x96.png
  packages/website/src/favicons/apple-icon-114x114.png
  packages/website/src/favicons/apple-icon-120x120.png
  packages/website/src/favicons/apple-icon-144x144.png
  packages/website/src/favicons/apple-icon-152x152.png
  packages/website/src/favicons/apple-icon-180x180.png
  packages/website/src/favicons/apple-icon-57x57.png
  packages/website/src/favicons/apple-icon-60x60.png
  packages/website/src/favicons/apple-icon-72x72.png
  packages/website/src/favicons/apple-icon-76x76.png
  packages/website/src/favicons/apple-icon-precomposed.png
  packages/website/src/favicons/apple-icon.png
  packages/website/src/favicons/browserconfig.xml
  packages/website/src/favicons/favicon-16x16.png
  packages/website/src/favicons/favicon-32x32.png
  packages/website/src/favicons/favicon-96x96.png
  packages/website/src/favicons/favicon.ico
  packages/website/src/favicons/manifest.json
  packages/website/src/favicons/ms-icon-144x144.png
  packages/website/src/favicons/ms-icon-150x150.png
  packages/website/src/favicons/ms-icon-310x310.png
  packages/website/src/favicons/ms-icon-70x70.png
  packages/website/src/index.html
  packages/website/types/index.d.ts
  yarn.lock
Labels: ✅ Can merge

#431 Add components for Identification
  docs/components/avatar.md
  docs/components/breadcrumb.md
  docs/components/breakdown.md
  docs/components/button.md
  docs/components/card.md
  docs/components/checkbox.md
  docs/components/chip.md
  docs/components/context-menu.md
  docs/components/date-picker.md
  docs/components/grid.md
  docs/components/icon.md
  docs/components/input.md
  docs/components/message.md
  docs/components/modal.md
  packages/components/lib/Avatar.d.ts
  packages/components/lib/Avatar.js
  packages/components/lib/Avatar.js.map
  packages/components/lib/AvatarGroup.d.ts
  packages/components/lib/AvatarGroup.js
  packages/components/lib/AvatarGroup.js.map
  packages/components/lib/index.d.ts
  packages/components/lib/index.js
  packages/components/lib/index.js.map
  packages/components/scripts/dev-server/index.tsx
  packages/components/src/Avatar.tsx
  packages/components/src/AvatarGroup.tsx
  packages/components/src/index.ts
  packages/website/src/Sections/Components/Avatars.tsx
  packages/website/src/Sections/Components/Selects.tsx
  packages/website/src/Sections/Components/index.ts
Labels: ✅ Can merge

#448 Error message dismiss
  packages/components/lib/Progress.d.ts
  packages/components/lib/Progress.js
  packages/components/lib/Progress.js.map
  packages/components/scripts/dev-server/index.tsx
  packages/components/src/Progress.tsx
Labels: ✅ Can merge

#447 Add range and stacked rendering to charts.
  docs/visualizations/chart.md
  packages/visual-tests/src/TestCases/Chart/area-3.ts
  packages/visual-tests/src/TestCases/Chart/area-4.ts
  packages/visual-tests/src/TestCases/Chart/bars-3.ts
  packages/visual-tests/src/TestCases/Chart/bars-4.ts
  packages/visual-tests/src/TestCases/Chart/index.ts
  packages/visual-tests/src/TestCases/Chart/range-1.ts
  packages/visual-tests/src/TestCases/Chart/range-2.ts
  packages/visualizations/lib/Chart/facade.js.map
  packages/visualizations/lib/Chart/series/renderer.d.ts
  packages/visualizations/lib/Chart/series/renderer.js.map
  packages/visualizations/lib/Chart/series/renderers/area.d.ts
  packages/visualizations/lib/Chart/series/renderers/area.js
  packages/visualizations/lib/Chart/series/renderers/area.js.map
  packages/visualizations/lib/Chart/series/renderers/bars.d.ts
  packages/visualizations/lib/Chart/series/renderers/flag.d.ts
  packages/visualizations/lib/Chart/series/renderers/line.d.ts
  packages/visualizations/lib/Chart/series/renderers/symbol.d.ts
  packages/visualizations/lib/Chart/series/renderers/text.d.ts
  packages/visualizations/lib/Chart/series/series.d.ts
  packages/visualizations/lib/Chart/series/series.js.map
  packages/visualizations/lib/Chart/series_manager.d.ts
  packages/visualizations/lib/Chart/series_manager.js
  packages/visualizations/lib/Chart/series_manager.js.map
  packages/visualizations/lib/Chart/typings.d.ts
  packages/visualizations/scripts/dev-server/site_chart.tsx
  packages/visualizations/src/Chart/facade.ts
  packages/visualizations/src/Chart/series/renderer.ts
  packages/visualizations/src/Chart/series/renderers/area.ts
  packages/visualizations/src/Chart/series/renderers/bars.ts
  packages/visualizations/src/Chart/series/renderers/flag.ts
  packages/visualizations/src/Chart/series/renderers/line.ts
  packages/visualizations/src/Chart/series/renderers/symbol.ts
  packages/visualizations/src/Chart/series/renderers/text.ts
  packages/visualizations/src/Chart/series/series.ts
  packages/visualizations/src/Chart/series_manager.ts
  packages/visualizations/src/Chart/typings.ts
Labels: visualizations, ✅ Can merge

#458 Remove lib folders and update build scripts
  .gitignore
  package.json
  scripts/ci.sh
Labels: ✅ Can merge

#459 Fix messages
  packages/components/lib/Message/Message.js
  packages/components/lib/Message/Message.js.map
  packages/components/lib/Messages/Messages.d.ts
  packages/components/lib/Messages/Messages.js
  packages/components/lib/Messages/Messages.js.map
  packages/components/lib/index.d.ts
  packages/components/lib/index.js
  packages/components/lib/index.js.map
  packages/components/scripts/dev-server/index.tsx
  packages/components/src/Message/Message.tsx
  packages/components/src/Messages/Messages.tsx
  packages/components/src/Messages/README.md
  packages/components/src/__tests__/__snapshots__/Message.test.tsx.snap
  packages/components/src/index.ts
Labels: ✅ Can merge

#461 Fix message padding
  packages/components/src/Message/Message.tsx
  packages/components/src/__tests__/__snapshots__/Message.test.tsx.snap
Labels: ✅ Can merge

#462 Fix length of text in sunburst breadcrumbs.
  packages/visualizations/scripts/dev-server/site_sunburst.tsx
  packages/visualizations/src/Sunburst/breadcrumb.ts
  packages/visualizations/src/Sunburst/styles.ts
Labels: visualizations, ✅ Can merge

#463 Fix progress dismiss handler
  packages/components/src/Progress/Progress.tsx
Labels: ✅ Can merge

#455 Button spinner
  packages/components/scripts/dev-server/index.tsx
  packages/components/src/Button/Button.tsx
  packages/components/src/Spinner/Spinner.tsx
  packages/components/src/__tests__/__snapshots__/Button.test.tsx.snap
  packages/components/src/__tests__/__snapshots__/ButtonGroup.test.tsx.snap
  packages/components/src/__tests__/__snapshots__/Spinner.test.tsx.snap
  packages/theme/src/utils.ts
Labels: ✅ Can merge

#450 Feature/chart focus
  docs_legacy/visualizations/chart.md
  packages/visual-tests/src/TestCases/Chart/bars-2.ts
  packages/visualizations/scripts/dev-server/site_chart.tsx
  packages/visualizations/src/Chart/axes/axis_utils.ts
  packages/visualizations/src/Chart/axes/categorical_axis.ts
  packages/visualizations/src/Chart/axes/quant_axis.ts
  packages/visualizations/src/Chart/axes/time_axis.ts
  packages/visualizations/src/Chart/canvas.ts
  packages/visualizations/src/Chart/facade.ts
  packages/visualizations/src/Chart/focus.ts
  packages/visualizations/src/Chart/focus/date_focus.ts
  packages/visualizations/src/Chart/focus/element_focus.ts
  packages/visualizations/src/Chart/focus/flag_focus.ts
  packages/visualizations/src/Chart/focus/styles.ts
  packages/visualizations/src/Chart/legend/legend.ts
  packages/visualizations/src/Chart/series/renderers/bars.ts
  packages/visualizations/src/Chart/series/renderers/flag.ts
  packages/visualizations/src/Chart/series/renderers/symbol.ts
  packages/visualizations/src/Chart/series/renderers/text.ts
  packages/visualizations/src/Chart/series/series.ts
  packages/visualizations/src/Chart/series_manager.ts
  packages/visualizations/src/Chart/styles.ts
  packages/visualizations/src/Chart/typings.ts
  packages/visualizations/src/PieChart/focus.ts
  packages/visualizations/src/PieChart/legend.ts
  packages/visualizations/src/PieChart/typings.ts
  packages/visualizations/src/utils/component_focus.ts
  packages/visualizations/src/utils/focus_utils.ts
  packages/visualizations/src/utils/quant_axis_utils.ts
  packages/visualizations/src/utils/state.ts
  packages/visualizations/src/utils/styles.ts
  packages/visualizations/src/utils/typings.ts
Labels: visualizations, ✅ Can merge

#452 Deprecation
  packages/blocks/.npmignore
  packages/blocks/.prettierrc
  packages/blocks/README.md
  packages/blocks/package.json
  packages/blocks/scripts/dev-server/index.html
  packages/blocks/scripts/dev-server/index.tsx
  packages/blocks/src/Auth.tsx
  packages/blocks/src/Filter.tsx
  packages/blocks/src/__tests__/Filter.test.tsx
  packages/blocks/src/index.ts
  packages/blocks/test-polyfills.js
  packages/blocks/tsconfig.json
  packages/blocks/tslint.json
  packages/components/scripts/dev-server/index.tsx
  packages/components/src/Progress/Progress.tsx
  packages/components/src/Table/Table.tsx
  packages/components/src/utils/deprecate.tsx
  packages/visualizations/src/Chart/focus/flag_focus.ts
  packages/visualizations/src/utils/quant_axis_utils.ts
  packages/visualizations/src/utils/state.ts
  yarn.lock
Labels: ✅ Can merge

#467 Card redesign
  packages/components/src/Card/Card.tsx
  packages/components/src/CardHeader/CardHeader.tsx
  packages/components/src/__tests__/__snapshots__/Card.test.tsx.snap
Labels: Work in Progress
